# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_app:
    name: Build App
    runs-on: ubuntu-latest
    steps:
    - name: Check repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gallery-artifact
        path: src/bin
  push_to_registry:
    name: Build & Push Docker image to hub
    needs: build_app
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v4
      - name: Create folder structure
        run: mkdir -p src/bin
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: gallery-artifact
          path: src/bin
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build & Push Docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: redbearddev/vsixgallery:latest
